name: object_detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - glib
  - libgl-devel
  - av
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torch
    - torchvision
    - ultralytics
    - streamlit
    - opencv-python-headless
    - numpy
    - pillow
    - pandas
    - streamlit-webrtc
    - tornado<6.2
